import { basename } from "node:path";

/**
 * The project's OWN markdown, beyond the files a tool is known to write.
 *
 * `RULE_FILES` names the documents whose path proves their purpose — a `CLAUDE.md` is instructions because
 * Claude Code reads it as instructions. A project's conventions are rarely only there. Measured on a real
 * one: `CLAUDE.md` held 109 KB, and beside it sat 453 more markdown files, among them the architecture notes
 * and standards every agent would otherwise rebuild from scratch.
 *
 * Taking "every .md file" literally is the trap, and the same measurement shows why. Those 454 files are
 * 6.8 MB, and the extractor splits prose into 8 KB slices — roughly 850 classification calls to produce the
 * 25 rules `MAX_RULES` keeps. Most of that is not instruction at all: dated handoffs, an archive directory of
 * completed reviews, pasted chat logs, and a 387 KB report a tool generated.
 *
 * So discovery is wide and the exclusions are stated. Nothing is dropped for being long or unfamiliar; a file
 * is set aside only when its path says what it is, and the caller is told what was set aside and why, so the
 * judgement can be argued with rather than merely obeyed.
 */

/** A candidate, or a file deliberately passed over with the reason attached. */
export interface DocCandidate {
  path: string;
  bytes: number;
  /** Absent when it is a candidate; the reason it was set aside when it is not. */
  skipped?: string;
}

/**
 * Paths that cannot be instructions, whatever they contain.
 *
 * The traces are the sharp one, and the reason is not their number. A trace DESCRIBES a source file — it is
 * derived FROM the code — so mining it for rules would turn "this module parses tokens" into a rule about how
 * the project should be written. It is the code talking back to itself.
 */
const DERIVED = [
  { re: /^\.horsecode\//, why: "horse-code's own state — traces describe the code, so rules mined from them would be the code talking back to itself" },
  { re: /^graphify-out\//, why: "generated by the graph build" },
  { re: /(^|\/)(node_modules|vendor|third_party|\.git)\//, why: "not this project's writing" },
  { re: /(^|\/)\.claude\/worktrees\//, why: "a nested checkout of this repository" },
];

/**
 * Paths whose name says they are a RECORD of what happened, not a statement of how things are done.
 *
 * A dated file is the clearest case: `HANDOFF-2026-06-02.md` was true on that day and describes a moment. A
 * rule has no date. `archive/` says the same thing about a whole directory, and a pasted chat log is a
 * conversation, not a convention.
 *
 * This is a judgement and it is reported as one. A project that keeps its standards in `docs/archive` gets
 * the wrong answer here — which is why the skipped list is shown rather than silently applied.
 */
const HISTORY = [
  { re: /(^|\/)archive(d)?\//i, why: "an archive of finished work" },
  { re: /\d{4}-\d{2}-\d{2}/, why: "dated — a record of a moment, not a standing rule" },
  { re: /(^|\/)(HANDOFF|RESUME|CHANGELOG|RELEASE[-_]NOTES)[^/]*$/i, why: "a record of what happened" },
  { re: /(^|\/)chats?\//i, why: "a pasted conversation" },
  { re: /(^|\/)chat\d*\.md$/i, why: "a pasted conversation" },
];

/**
 * Sorts the project's markdown into what is worth reading for rules and what is not.
 *
 * `known` is the set already covered by name — `CLAUDE.md` and its siblings — which are imported through
 * their own path and must not be imported twice.
 */
export function sortProjectDocs(
  files: { path: string; bytes: number }[],
  known: readonly string[] = [],
): { candidates: DocCandidate[]; skipped: DocCandidate[] } {
  const seen = new Set(known.map((k) => k.replace(/\\/g, "/")));
  const candidates: DocCandidate[] = [];
  const skipped: DocCandidate[] = [];
  for (const f of files) {
    const path = f.path.replace(/\\/g, "/");
    if (!/\.mdx?$/i.test(path)) continue;
    if (seen.has(path) || seen.has(basename(path))) continue;
    const why = DERIVED.find((d) => d.re.test(path))?.why ?? HISTORY.find((h) => h.re.test(path))?.why;
    if (why) skipped.push({ path, bytes: f.bytes, skipped: why });
    else candidates.push({ path, bytes: f.bytes });
  }
  const bySize = (a: DocCandidate, b: DocCandidate): number => b.bytes - a.bytes;
  return { candidates: candidates.sort(bySize), skipped: skipped.sort(bySize) };
}

/** Total size of a set, for a sentence about what a run will cost. */
export function totalBytes(docs: readonly DocCandidate[]): number {
  return docs.reduce((n, d) => n + d.bytes, 0);
}

/**
 * What reading them will cost, in the extractor's own unit.
 *
 * Stated before anything is spent, because the number is the whole argument for asking first: on the project
 * this was written for, the unfiltered set came to roughly 850 calls to produce 25 rules.
 */
export function classifyCalls(bytes: number, chunk: number): number {
  return Math.max(1, Math.ceil(bytes / chunk));
}
